name: Terraform CI

on:
  push:
    branches:
      - Dev
      - Test
  pull_request:
    branches:
      - Dev
      - Test

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt (check formatting)
        run: terraform fmt -check

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      # AJOUT : configuration AWS dans GitHub Actions 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color > plan.txt

      - name: comment terraform plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          header: terraform-plan
          path: plan.txt