name: Terraform DESTROY (manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement à appliquer"
        required: true
        default: "Dev"
        type: choice
        options:
          - Dev
          - Test
          - Prod

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve